/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.xml.*;


public class EditProductFrom extends javax.swing.JFrame {

    /**
     * Creates new form EditProductFrom
     */
    public EditProductFrom() {
        initComponents();
    }
    
    static final String DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost:3306/cakeshop";
    static final String USER = "root";
    static final String PASS = "";
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelECategeroy = new javax.swing.JLabel();
        jLabelEName = new javax.swing.JLabel();
        jLabelEQuantity = new javax.swing.JLabel();
        jLabelEPrice = new javax.swing.JLabel();
        jLabelEDescription1 = new javax.swing.JLabel();
        jTextFieldQun = new javax.swing.JTextField();
        jComboBoxCat = new javax.swing.JComboBox<>();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDes = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButtonEClear = new javax.swing.JButton();
        jButtonEClose = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jLabelId4 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 28, 62));

        jLabelECategeroy.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabelECategeroy.setForeground(new java.awt.Color(255, 255, 255));
        jLabelECategeroy.setText("Category");

        jLabelEName.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabelEName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEName.setText("Name");

        jLabelEQuantity.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabelEQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEQuantity.setText("Quantity");

        jLabelEPrice.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabelEPrice.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEPrice.setText("Price");

        jLabelEDescription1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabelEDescription1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEDescription1.setText("Description");

        jComboBoxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextAreaDes.setColumns(15);
        jTextAreaDes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDes);

        jLabel2.setBackground(new java.awt.Color(0, 102, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("EDIT NEW ITEM");

        jButtonEClear.setBackground(new java.awt.Color(0, 102, 204));
        jButtonEClear.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonEClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEClear.setText("CLEAR");
        jButtonEClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEClearActionPerformed(evt);
            }
        });

        jButtonEClose.setBackground(new java.awt.Color(255, 0, 0));
        jButtonEClose.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonEClose.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEClose.setText("CLOSE");
        jButtonEClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonECloseActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(0, 153, 0));
        jButtonEdit.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonEdit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEdit.setText("EDIT");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jLabelId4.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabelId4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId4.setText("Product ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelId4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jButtonEClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                        .addComponent(jButtonEClose, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelECategeroy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCat, 0, 193, Short.MAX_VALUE)
                                    .addComponent(jTextFieldQun, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jTextFieldId))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelECategeroy, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabelEDescription1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldQun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEClose)
                    .addComponent(jButtonEClear)
                    .addComponent(jButtonEdit))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonECloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonECloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonECloseActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        if(jTextFieldId.getText().equals("")){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER CATEGORY ID WHIVH WANT TO UPDATE");}
        
        else if(jComboBoxCat.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(null,"PLEASE SELECT CATEGORY ");}
        
        
        else if(jTextFieldName.getText().equals("")){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER PRODUCT Name");}
        
         else if(jTextFieldQun.getText().equals("")){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER PRODUCT Quantity");}
         
          else if(jTextFieldPrice.getText().equals("")){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER PRODUCT PRICE");}
        
           else if(jTextAreaDes.getText().equals("")){
                JOptionPane.showMessageDialog(null,"PLEASE ENTER PRODUCT DESCRIPTION");}
        else{
        Connection con = null;
        PreparedStatement sta = null;
        

        try {
            
            Class.forName(DRIVER);

         
            con = DriverManager.getConnection(DB_URL, USER, PASS);
           

            
            String sql = "UPDATE product_detail SET category=?,pro_name=?,Quantity=?,price=?,description=? Where pro_id=?";
            sta = (PreparedStatement) con.prepareStatement(sql);
            
            
             
            sta.setString(1, String.valueOf(jComboBoxCat.getSelectedItem()));
            sta.setString(2, jTextFieldName.getText());
            sta.setDouble(3, Double.parseDouble(jTextFieldQun.getText()));
            sta.setDouble(4, Double.parseDouble(jTextFieldPrice.getText()));
            sta.setString(5, jTextAreaDes.getText());
            sta.setInt(6,Integer.parseInt( jTextFieldId.getText()));
            int res = sta.executeUpdate();
            JOptionPane.showMessageDialog(null,"DATA UPDATED SUCESSFULLY");
         
            
            jTextFieldId.setText("");
            jTextFieldName.setText("");
            jComboBoxCat.setSelectedItem("");
            jTextFieldQun.setText("");
            jTextFieldPrice.setText("");
            jTextAreaDes.setText("");
            
        
           
            

               
               
           

        } catch (SQLException ex) {
            
            ex.printStackTrace();
        } catch (Exception ex) {
            
            ex.printStackTrace();
        } finally {
            
            try {
                if (sta != null) {
                    sta.close();
                  
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

            try {
                if (con != null) {
                    con.close();
                    
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonEClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEClearActionPerformed
        // TODO add your handling code here:
        
        jTextFieldId.setText("");
            jTextFieldName.setText("");
            jComboBoxCat.setSelectedItem("");
            jTextFieldQun.setText("");
            jTextFieldPrice.setText("");
            jTextAreaDes.setText("");
            
    }//GEN-LAST:event_jButtonEClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProductFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProductFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProductFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProductFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProductFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEClear;
    private javax.swing.JButton jButtonEClose;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JComboBox<String> jComboBoxCat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelECategeroy;
    private javax.swing.JLabel jLabelEDescription1;
    private javax.swing.JLabel jLabelEName;
    private javax.swing.JLabel jLabelEPrice;
    private javax.swing.JLabel jLabelEQuantity;
    private javax.swing.JLabel jLabelId4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDes;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldQun;
    // End of variables declaration//GEN-END:variables
}
