/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.xml.*;
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }

     static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost:3306/cakeshop";
    static final String USER = "root";
    static final String PASS = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelEId = new javax.swing.JLabel();
        jLabelEName = new javax.swing.JLabel();
        jLabelEAdd = new javax.swing.JLabel();
        jLabelETel = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelEEmail = new javax.swing.JLabel();
        jLabelEPas = new javax.swing.JLabel();
        jTextFieldEId = new javax.swing.JTextField();
        jTextFieldEAdd = new javax.swing.JTextField();
        jTextFieldEName = new javax.swing.JTextField();
        jTextFieldEEmail = new javax.swing.JTextField();
        jTextFieldETel = new javax.swing.JTextField();
        jTextFieldEPas = new javax.swing.JTextField();
        jTextFieldEUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmp = new javax.swing.JTable();
        jButtonInsert = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 66, 108));

        jLabelEId.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabelEId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEId.setText("Employee ID");

        jLabelEName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabelEName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEName.setText("Employee Name");

        jLabelEAdd.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabelEAdd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEAdd.setText("Employee Address");

        jLabelETel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabelETel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelETel.setText("Telephone No");

        jLabelUser.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setText("User Name");

        jLabelEEmail.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabelEEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEEmail.setText("Eployee Email");

        jLabelEPas.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabelEPas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEPas.setText("Password");

        jTableEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Address", "Telephone", "Email", "User Name", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTableEmp);

        jButtonInsert.setBackground(new java.awt.Color(0, 102, 0));
        jButtonInsert.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonInsert.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert.setText("INSERT");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(0, 51, 255));
        jButtonUpdate.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Update ");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonView.setBackground(new java.awt.Color(102, 102, 0));
        jButtonView.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonView.setForeground(new java.awt.Color(255, 255, 255));
        jButtonView.setText("View ");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jButtonRemove.setBackground(new java.awt.Color(153, 0, 0));
        jButtonRemove.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButtonRemove.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemove.setText("Remove ");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(255, 153, 0));
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("CLEAR");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEId)
                            .addComponent(jLabelEName)
                            .addComponent(jLabelEAdd)
                            .addComponent(jLabelETel)
                            .addComponent(jLabelUser)
                            .addComponent(jLabelEEmail)
                            .addComponent(jLabelEPas))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEPas, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldETel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEUser, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEId)
                                    .addComponent(jTextFieldEId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEName)
                                    .addComponent(jTextFieldEName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEAdd)
                                    .addComponent(jTextFieldEAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelETel)
                                    .addComponent(jTextFieldETel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEEmail)
                                    .addComponent(jTextFieldEEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelUser)
                                    .addComponent(jTextFieldEUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEPas)
                                    .addComponent(jTextFieldEPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonView, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void updateTable(){
    Connection con = null;
        Statement sta = null;

        try {
            
            Class.forName(JDBC_DRIVER);

         
            con = DriverManager.getConnection(DB_URL, USER, PASS);

            sta = con.createStatement();
            String sql = "SELECT * FROM employee_detail";
           
            ResultSet rs = sta.executeQuery(sql);
            ResultSetMetaData rsmetadata=rs.getMetaData();
            int columns=rsmetadata.getColumnCount();
            DefaultTableModel dtm=new DefaultTableModel();
            Vector columns_name= new Vector();
            Vector data_raws=new Vector();
            
            for(int i=1; i<=columns; i++){
                columns_name.addElement(rsmetadata.getColumnName(i));
           
            }
            dtm.setColumnIdentifiers(columns_name);

           
            while (rs.next()) {
                data_raws=new Vector();
                for(int j=1; j<=columns;j++){
                    data_raws.addElement(rs.getString(j));
                
                }
                dtm.addRow(data_raws);
                jTableEmp.setModel(dtm);
                
                

               
               
            }

           
            rs.close();

        } catch (SQLException ex) {
            
            ex.printStackTrace();
        } catch (Exception ex) {
            
            ex.printStackTrace();
        } finally {
            
            try {
                if (sta != null) {
                    sta.close();
                  
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

            try {
                if (con != null) {
                    con.close();
                    
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
    
    }
    
    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        Connection con = null;
        PreparedStatement pst = null;

        if(jTextFieldEId.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Employee ID");}

        else if(jTextFieldEName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Empolyee Name");}
         else if(jTextFieldEAdd.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Empolyee Address");}


        else if(jTextFieldETel.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER CUStOMER TELEPHONE NO");}
        else if(jTextFieldEEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER CUStOMER EMAIL");}
         else if(jTextFieldEUser.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Empolyee User Name");}

          else if(jTextFieldEPas.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Empolyee Password");}


        else{
            try {

                Class.forName(JDBC_DRIVER);
                con = DriverManager.getConnection(DB_URL, USER, PASS);
                String query = "INSERT INTO employee_detail(e_id,e_name, e_address,e_tel,e_email,e_user,e_password) VALUES (?,?,?,?,?,?,?)";
                pst = (PreparedStatement) con.prepareStatement(query);

                pst.setInt(1, Integer.parseInt(jTextFieldEId.getText()));
                pst.setString(2, jTextFieldEName.getText());
                pst.setString(3, jTextFieldEAdd.getText());
                pst.setString(4, jTextFieldETel.getText());
                 pst.setString(5, jTextFieldEEmail.getText());
                pst.setString(6, jTextFieldEUser.getText());
                pst.setString(7, jTextFieldEPas.getText());
                int res = pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"DATA ADDED SUCESSFULLY");
                updateTable();

                jTextFieldEId.setText("");
                jTextFieldEName.setText("");
                jTextFieldETel.setText("");
                jTextFieldEEmail.setText("");
                jTextFieldEAdd.setText("");
                jTextFieldEUser.setText("");
                jTextFieldEPas.setText("");
            } catch (SQLException ex) {

                ex.printStackTrace();
            } catch (Exception ex) {

                ex.printStackTrace();
            } finally {

                try {
                    if (pst != null) {
                        pst.close();

                    }
                } catch (SQLException se2) {

                }
                try {
                    if (con != null) {
                        con.close();

                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
                 if(jTextFieldEId.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Employee ID");}

        else if(jTextFieldEName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Employee Name");}
        else if(jTextFieldEAdd.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Employee Address");}
        
        else if(jTextFieldETel.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER CUStOMER TELEPHONE NO");}
        else if(jTextFieldEEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER CUStOMER EMAIL");}
        else if(jTextFieldEUser.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Employee USER Name");}
        else if(jTextFieldEPas.getText().equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER Employee Password");}

        else{
            Connection con = null;
            PreparedStatement sta = null;

            try {

                Class.forName(JDBC_DRIVER);

                con = DriverManager.getConnection(DB_URL, USER, PASS);

                String sql = "UPDATE employee_detail SET e_name=?,e_address=?,e_tel=?,e_email=?,e_user=?,e_password=? Where e_id=?";
                sta = (PreparedStatement) con.prepareStatement(sql);

                sta.setString(1, jTextFieldEName.getText());
                sta.setString(2, jTextFieldEAdd.getText());
                sta.setString(3, jTextFieldETel.getText());
                sta.setString(4, jTextFieldEEmail.getText());
                sta.setString(5, jTextFieldEUser.getText());
                sta.setString(6, jTextFieldEPas.getText());
                sta.setInt(7,Integer.parseInt( jTextFieldEId.getText()));

                sta.executeUpdate();

                JOptionPane.showMessageDialog(this,"sucssesfuly Updated");
                updateTable();
                jTextFieldEId.setText("");
                jTextFieldEName.setText("");
                jTextFieldETel.setText("");
                jTextFieldEEmail.setText("");
                jTextFieldEAdd.setText("");
                jTextFieldEUser.setText("");
                jTextFieldEPas.setText("");


            } catch (SQLException ex) {

                ex.printStackTrace();
            } catch (Exception ex) {

                ex.printStackTrace();
            } finally {

                try {
                    if (sta != null) {
                        sta.close();

                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }

                try {
                    if (con != null) {
                        con.close();

                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        // TODO add your handling code here:

        updateTable();
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
       if(jTableEmp.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null,"Please Select Item to delete");

        }
        else{
            int row=jTableEmp.getSelectedRow();

            String cell=jTableEmp.getModel().getValueAt(row, 0).toString();

            Connection con = null;
            PreparedStatement sta = null;

            try {

                Class.forName(JDBC_DRIVER);

                con = DriverManager.getConnection(DB_URL, USER, PASS);

                String sql = "DELETE FROM employee_detail WHERE e_id= " +cell;
                sta = (PreparedStatement) con.prepareStatement(sql);

                sta.execute();
                JOptionPane.showMessageDialog(null,"sucssesfuly Delceted");

                updateTable();

            } catch (SQLException ex) {

                ex.printStackTrace();
            } catch (Exception ex) {

                ex.printStackTrace();
            } finally {

                try {
                    if (sta != null) {
                        sta.close();

                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }

                try {
                    if (con != null) {
                        con.close();

                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
         jTextFieldEId.setText("");
                jTextFieldEName.setText("");
                jTextFieldETel.setText("");
                jTextFieldEEmail.setText("");
                jTextFieldEAdd.setText("");
                jTextFieldEUser.setText("");
                jTextFieldEPas.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabelEAdd;
    private javax.swing.JLabel jLabelEEmail;
    private javax.swing.JLabel jLabelEId;
    private javax.swing.JLabel jLabelEName;
    private javax.swing.JLabel jLabelEPas;
    private javax.swing.JLabel jLabelETel;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmp;
    private javax.swing.JTextField jTextFieldEAdd;
    private javax.swing.JTextField jTextFieldEEmail;
    private javax.swing.JTextField jTextFieldEId;
    private javax.swing.JTextField jTextFieldEName;
    private javax.swing.JTextField jTextFieldEPas;
    private javax.swing.JTextField jTextFieldETel;
    private javax.swing.JTextField jTextFieldEUser;
    // End of variables declaration//GEN-END:variables
}
